### ISSUE TITLE
why the page get http status 500？

### ISSUE THREAD

**Issue by zhuxindong** [aquasecurity/vuln-list#27]
the page “https://github.com/aquasecurity/vuln-list/” got status 500 in anytime
![image](https://user-images.githubusercontent.com/24989246/222659282-9427b4b3-e6cf-4316-9114-d87cdad0311b.png)

**Comment by CardLove** [comment]
Has the problem been solved

**Comment by zhuxindong** [comment]
no ,the page https://github.com/aquasecurity/vuln-list/ still reponse in code 500

![image](https://user-images.githubusercontent.com/24989246/224539131-715b8b88-f17c-4fb0-8a87-e568b1d0879a.png)

**Comment by knqyf263** [comment]
We worked with the GitHub support team and reduced the repository size to address the 500 issue. We separated some data into [vuln-list-redhat](https://github.com/aquasecurity/vuln-list-redhat) and [vuln-list-debian](https://github.com/aquasecurity/vuln-list-debian) and cleaned the commit history. It should be fine now.

**Comment by thcdrt** [comment]
> Hello, there is still the issue :'(

And now it seems to work again, it's really weird...
